# Site settings
title: Adventures in FreeCodeCamp
email: reggie1se@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Solving problems and working on projects in FreeCodeCamp
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reggie01.github.io./" # the base hostname & protocol for your site
twitter_username: ReggieSanders7
github_username:  Reggie01

# Build settings
markdown: kramdown
encoding: utf-8
safe: true
lsi: false
#source: your top-level directory
highlighter: pygments
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
github: [{
  "hostname": "github.com",
  "pages_hostname": "github.io",
  "environment": "dotcom",
  "project_tagline": "A Github Pages site to showcase progress on FreeCodeCamp"
, 
}]
