# Site settings
title: Jedawan | A journey to JS mastery
email: reggie1se@gmail.com
description: "This blog is about modern web development."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reggie01.github.io./" # the base hostname & protocol for your site
twitter_username: Reggie0_0
github_username:  Reggie01
author: reggie
image: https://images.unsplash.com/photo-1456472821979-5120d02321ab?auto=format&fit=crop&w=889&q=80

# Google services
google_analytics: 'UA-93729832-1'

# Build settings
markdown: kramdown
encoding: utf-8
safe: true
lsi: false

#source: your top-level directory
highlighter: pygments
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
github: [{
  "hostname": "github.com",
  "pages_hostname": "github.io",
  "environment": "dotcom",
  "project_tagline": "A Github Pages site to showcase progress on FreeCodeCamp"
, 
}]

gems:
  - jekyll-sitemap